language: objective-c  #1
osx_image: xcode9.2 #2
xcode_project: BitFiddle.xcodeproj #3
xcode_scheme: BitFiddle #4
xcode_sdk: iphonesimulator11.2

before_install:
  - gem install cocoapods -v '1.4.0'

script:
  - xcodebuild -project BitFiddle.xcodeproj -scheme BitFiddle -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
  - xcodebuild test -project BitFiddle.xcodeproj -scheme BitFiddle -destination 'platform=iOS Simulator,name=iPhone 6,OS=11.2' -sdk iphonesimulator
  - pod lib lint
